<p>Authentication</p>
<ul>
    <a target="_blank" href="http://httpd.apache.org/docs/2.0/howto/auth.html">Authentication, Authorization and Access Control - Apache 2.0</a><br>
    <a target="_blank" href="http://www.php.net/manual/en/features.http-auth.php">HTTP authentication with PHP</a><br>
    <a target="_blank" href="http://httpd.apache.org/docs/2.0/mod/mod_auth_ldap.html">Apache Module mod_auth_ldap</a><br>
</ul>
<p>LDAP - OpenLDAP</p>
<ul>
    <a target="_blank" href="http://directory.apache.org/">The Apache Directory Project</a><br>
</ul>
<p>Scripts</p>
<ul>
    <p>Certificates</p>
    <ul>
        <a target="_blank" href="showScript.php?file=genCertificate.bat">genCertificate.bat</a><br>
        <a target="_blank" href="showScript.php?file=genCertificate.sh">genCertificate.sh</a><br>
    </ul>
    <p>Account Management</p>
    <ul>
        <a target="_blank" href="showScript.php?file=createUsers.bat">createUsers.bat</a><br>
    </ul>
</ul>